[project]
name = "image-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.14.3",
    "aiortc>=1.15.0",
    "keyboard>=0.13.5",
    "opencv-python>=5.0.0.93",
    "pymavlink>=2.4.49",
    "websockets>=17.1",
]
